# Generated by Django 3.0.5 on 2020-08-08 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200728_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 15, 9, 26, 178459)),
        ),
    ]
