# Generated by Django 3.0.5 on 2020-08-09 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200808_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 16, 47, 7, 211804)),
        ),
    ]
