# Generated by Django 3.0.5 on 2020-09-09 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200909_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 4, 25, 46, 742229)),
        ),
        migrations.AlterField(
            model_name='addblog',
            name='post',
            field=models.TextField(max_length=2000),
        ),
    ]
