# Generated by Django 3.0.5 on 2020-09-09 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200909_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 7, 9, 33, 822574)),
        ),
    ]
