# Generated by Django 3.0.5 on 2020-10-08 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201008_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 2, 55, 35, 229129)),
        ),
    ]
