# Generated by Django 3.1.3 on 2020-11-11 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201008_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 0, 10, 3, 680005)),
        ),
    ]
