# Generated by Django 3.0.5 on 2020-08-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useradd_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='pic',
            field=models.ImageField(upload_to='static/images/oio'),
        ),
    ]
