# Generated by Django 3.0.5 on 2020-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200808_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejister',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('cources', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
