# Generated by Django 3.0.5 on 2020-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rejister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejister',
            name='cources',
            field=models.CharField(max_length=50),
        ),
    ]
