# Generated by Django 3.0.5 on 2020-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201008_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejistermodal',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('cources', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Rejister',
        ),
    ]
